name: Test
env:
  GO111MODULE: true
  PYTHONPATH: /tmp/instr
  BASH_ENV: /tmp/instr/bash_env.sh
permissions:
  contents: read
jobs:
  lic-headers:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - run: docker run -v $(pwd):/wrk -w /wrk ghcr.io/google/addlicense -c 'The Cobra
        Authors' -y '2013-2023' -l apache -ignore '.github/**' -check .
    timeout-minutes: 12
  golangci-lint:
    permissions:
      contents: read
      pull-requests: read
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version: ^1.22
        check-latest: true
        cache: true
    - uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: latest
        args: --verbose
    timeout-minutes: 12
  test-unix:
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: ubuntu
          go: '17'
    name: ${{ matrix.platform }} | 1.${{ matrix.go }}.x
    runs-on: self-hosted
    env:
      GO_TEST_FLAGS: ${{ matrix.platform == 'macOS' && matrix.go < 24 && '-ldflags=-linkmode=external'
        || '' }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v6
      with:
        go-version: 1.${{ matrix.go }}.x
        cache: true
    - run: |
        export GOBIN=$HOME/go/bin
        go install github.com/kyoh86/richgo@latest
        go install github.com/mitchellh/gox@latest
    - run: RICHGO_FORCE_COLOR=1 PATH=$HOME/go/bin/:$PATH make richtest
    timeout-minutes: 12
'on':
  push: null
  pull_request: null
  workflow_dispatch: null
